service: aws-serverless-build-monitor

frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.9

functions:
  renderRepoDetails:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'
    - '!package.*'
    - '!Pipfile*'
    - 'templates/**'

custom:
  pythonRequirements:
    usePipenv: true
    invalidateCaches: true
    strip: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
        - "**/*.pyc"
        - "**/*.pyo"
        - "**/__pycache__*"