service: aws-serverless-build-monitor
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.9
  region: ${opt:region, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - arn:aws:s3:::${self:custom.bucketName}/*

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
  Outputs:
    WebsiteURL:
      Value: !GetAtt 
        - StaticSite
        - WebsiteURL
      Description: URL for website hosted on S3
    S3BucketSecureURL:
      Value: !Join 
        - ''
        - - 'https://'
          - !GetAtt 
            - StaticSite
            - DomainName
      Description: Name of S3 bucket to hold website content


functions:
  renderRepoDetails:
    handler: handler.run
    environment: 
      # https://www.serverless.com/blog/aws-secrets-management/
      GITHUB_TOKEN: ${ssm:/GITHUB_TOKEN}
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-python-requirements
  - serverless-s3-sync

package:
  patterns:
    - '!node_modules/**'
    - '!.venv'
    - '!package.*'
    - '!Pipfile*'
    - '!static/**'
    - '!*.md'
    - '!Makefile'
    - 'templates/**'

custom:
  bucketName: monitor.levelup-program.com
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: static
  pythonRequirements:
    usePipenv: false
    invalidateCaches: true
    strip: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
        - "**/*.pyc"
        - "**/*.pyo"
        - "**/__pycache__*"