service: aws-serverless-build-monitor
frameworkVersion: '3'

provider:
  name: aws
  region: ${opt:region, 'us-east-2'}
  stage: ${self:custom.currentStage}
  deploymentMethod: direct
  runtime: python3.9
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:345218099459:table/levelup*
            - arn:aws:dynamodb:${self:provider.region}:345218099459:table/levelup*/index/*


functions:
  api:
    handler: wsgi_handler.handler
    description: Level Up Build Monitor - Takes EventUID and list of team numbers as parameter
    environment:
      FLASK_ENV: development
      GITHUB_TOKEN: ${ssm:/GITHUB_TOKEN}
      LOGLEVEL: INFO
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager

package:
  patterns:
    - '!node_modules/**'
    - '!package.*'
    - '!Pipfile*'
    - '!*.md'
    - '!Makefile'
    - '!.venv'
    - '!dist'
    - 'templates/**'

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  wsgi:
    app: app.app
  pythonRequirements:
    usePipenv: false
    invalidateCaches: true
    strip: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
        - "**/*.pyc"
        - "**/*.pyo"
        - "**/__pycache__*"
  customDomain:
    domainName: monitor-${self:provider.stage}.levelup-program.com
    stage: ci
    basePath: api
    certificateName: '*.levelup-program.com'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false