name: Build and Test

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'README.md'
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Python Virtual Environment
        run: python -m pip install --upgrade pipenv

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Setup Serverless
        run: make bootstrap-serverless

      - id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/virtualenvs
            ./node_modules
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          make bootstrap-python

      - name: Test
        id: test
        run: make test

      - name: Deploy Dev
        if: ${{ github.ref == 'refs/heads/develop' && steps.test.outcome == 'success' }}
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make deploy-dev

      - name: Deploy Prod
        if: ${{ github.ref == 'refs/heads/main' && steps.test.outcome == 'success' && github.event.pull_request.merged == true }}
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make deploy-prod
